[package]
name = "clix-view"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "View Markdown files in terminal with inline rendered images."
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
clix-core = { path = "../clix-core" }
viuer.workspace = true
